### ISSUE TITLE
Bug in at pollyfill

### ISSUE THREAD

**Issue by heyitstay11** [siddhigate/js-polyfills#1]
## returns undefined for index zero
![IMG_20220912_010155](https://user-images.githubusercontent.com/74863317/189545922-9f730de8-265a-42c6-a6c5-60f1e2c958d7.jpg)
## Output
![IMG_20220912_010211](https://user-images.githubusercontent.com/74863317/189545950-e47de348-7281-4d40-9207-da2ccd2e3881.jpg)

Code looks for the element at the index equal to the length of the array

**Comment by birender** [comment]
I have added Error Handling.
allow me to add those method also

**Comment by siddhigate** [comment]
Thank you for raising this issue! Solved in #2 by @binarydevelop
